Module9 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #13
Opened 2021-02-02 04:08 UTC by elismountain

2021-02-02 04:11 UTC, elismountain commented
Алекс, помогите доделать эту хрень, я больше не могууу. Я поменяла структуру waypoints, чтобы удобнее было сделать инфо, теперь консоль ругвется, что waypoint равен нулю, все перерыла, не понимаю, почему туда ноль приходит

2021-02-02 16:31 UTC, AlexMasterov requested changes

2021-02-02 16:31 UTC, AlexMasterov commented on src/presenter/summary.js
> +    this._infoComponent = new InfoView();
<details>
<summary>view/info.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/242d0aa2cd5e4573e929166b6fb933879063216e/src/view/info.js#L59-L62
</details>
<details>
<summary>presenter/summary.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/242d0aa2cd5e4573e929166b6fb933879063216e/src/presenter/summary.js#L34
</details>

Конструктор класса `Info` используется параметр `waypoints`, но его экземпляр создается без аргументов и значением `waypoints` оказывается `undefined`.

Можно попробовать исправить так:
```diff
- this._infoComponent = new InfoView();
+ this._infoComponent = new InfoView(this._waypointsModel.getWaypoints());
```

2021-02-02 16:31 UTC, AlexMasterov commented on src/view/info.js
> +  let sortedDate = [];
```js
Array.isArray(sortedDate) // true
```

Б8

2021-02-02 16:31 UTC, AlexMasterov commented on src/view/statistics.js
> +        data: labels.map((t) => costs.get(t)),
`t`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

2021-02-02 16:31 UTC, AlexMasterov commented on src/view/statistics.js
> +        data: labels.map((t) => counts.get(t)),
`t`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

2021-02-02 16:31 UTC, AlexMasterov commented on src/view/statistics.js
> +        data: labels.map((t) => times.get(t)),
`t`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

2021-02-02 16:31 UTC, AlexMasterov commented on src/view/statistics.js
> +          formatter: (val) => `${val}D`
`val`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

2021-02-02 16:31 UTC, AlexMasterov commented on src/utils/statistics.js
> +    const travelHours = Math.floor((waypoint.startTime - waypoint.startTime) / 3600000 / 24);
`3600000`
`24`

Б31

2021-02-02 16:31 UTC, AlexMasterov commented on src/utils/statistics.js
> +  let result = [];
`result`

Б8

2021-02-02 16:31 UTC, AlexMasterov commented on src/utils/statistics.js
> +// export const getUniqueItems = (items) => [...new Set(items)];
`//`

Б18

2021-02-02 16:31 UTC, AlexMasterov commented on src/presenter/summary.js
>      const info = getTripInfo(this._waypointsModel.getWaypoints());
```
'info' is assigned a value but never used
```

Б15

2021-02-02 22:44 UTC, AlexMasterov requested changes

2021-02-02 22:44 UTC, AlexMasterov commented on src/presenter/summary.js
> +    this._headerContainer = headerContainer;
```js
headerContainer instanceof Element // true
```
Д6

😟

2021-02-02 22:44 UTC, AlexMasterov commented on src/presenter/waypoint.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L45-L46
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L48-L52
</details>

```js
this._cardElement instanceof Element     // false
this._cardEditElement instanceof Element // false
```
Д6

Это не [DOM-элементы](https://developer.mozilla.org/ru/docs/Web/API/Element).

Нужно убрать суффикс `Element`.

> В самом начале интенсива предупреждал, что лучше вообще не использовать суффикс `Element`. Очень много времени потратили на этот критерий 😟

2021-02-02 22:44 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106670858-a288d480-65be-11eb-9ded-612e36b230c1.png)

</details>

В отсутствия точек маршрута отображается дата со значением `undefined`.

Нужно убрать.

2021-02-02 22:44 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106671118-04e1d500-65bf-11eb-8296-9306c9bb163d.png)

![image](https://user-images.githubusercontent.com/700213/106671081-f98ea980-65be-11eb-91dc-5e14d9d4e7f2.png)
</details>

Не получается создать точку маршрута: `undefined, undefined`.

Нужно срочно исправить 😟

2021-02-02 22:44 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/106671339-63a74e80-65bf-11eb-9bfb-8b998a4f431b.png)

</details>

<details>
<summary>Ожидание (markup/list-empty.html)</summary>

![image](https://user-images.githubusercontent.com/700213/106671283-4bcfca80-65bf-11eb-8c69-d97c7765c0d2.png)

</details>

Текущая реализация немного не соответствует макету.

2021-02-02 22:44 UTC, AlexMasterov commented on src/view/edit-waypoint.js
>    _onWaypointTypeChangeHandler(evt) {
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L144-L152
</details>

_`on`WaypointTypeChange`Handler`
**и т.п.**

Д4

После нескольких исправлений снова используется сразу два варианта именования обработчиков DOM: `on` с `Handler`. По критерию нужно выбрать для всего проекта только один вариант.

См. [одно из прошлых замечаний](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/10#discussion_r566587042):
> **нужно выбрать _один_ и исправить во всем проекте**

2021-02-02 22:44 UTC, AlexMasterov commented on src/view/edit-waypoint.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L286-L287
</details>

.event__`type-list` + `change` !== this._onWaypoint`Type`ChangeHandler

Д4

2021-02-02 22:44 UTC, AlexMasterov commented on src/view/edit-waypoint.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L293
</details>

`offersRendered`Element + `change` !== this._on`OfferToggle`Handler

Д4

2021-02-02 22:44 UTC, AlexMasterov commented on src/view/edit-waypoint.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L417
</details>

```js
Array.isArray(allOffersForType) // true
```

Б8

2021-02-02 22:59 UTC, elismountain commented on src/main.js
Два часа уже ищу ее, не могу найти откуда это вылезло

2021-02-02 23:01 UTC, AlexMasterov requested changes

2021-02-02 23:01 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/menu.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/menu.js#L11
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/menu.js#L14
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/menu.js#L21
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/menu.js#L31
</details>

`Menu`._on`Menu`ClickHandler
`Menu`.set`Menu`ClickHandler
`Meni`.set`Menu`Item
и т.п.

Д3

До сих пор не исправлено 😟

2021-02-02 23:07 UTC, AlexMasterov requested changes

2021-02-02 23:07 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/smart.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/smart.js#L28
</details>

`let`

Б12

```diff
- let prevElement = this.getElement();
+ const prevElement = this.getElement();
```

> Этот модуль исправляли (также меняли `.replaceChild` на `replaceWith`), но в одном из задание он был полностью заменен 😕

2021-02-02 23:07 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/sort.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/sort.js#L30
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/sort.js#L33-L34
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/sort.js#L41
</details>

`Sort`._current`Sort`Type
`Sort`._on`Sort`TypeChangeHandler
`Sort`.set`Sort`TypeChangeHandler
**и т.п.**

Д3 (чтоб его!)

До сих пор не исправлено 😟

2021-02-02 23:12 UTC, AlexMasterov commented on src/main.js
> Два часа уже ищу ее, не могу найти откуда это вылезло

<details>
<summary>presenter/trip.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/trip.js#L42
</details>

```js
this._cardsListElement // undefined
```

Проблема здесь 😃

2021-02-02 23:15 UTC, elismountain commented on src/main.js
Аааа, почему линтер не ругается на такое

2021-02-02 23:15 UTC, AlexMasterov requested changes

2021-02-02 23:15 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/filter.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/filter.js#L6
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/filter.js#L9
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/filter.js#L12-L13
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/filter.js#L16
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/filter.js#L18
</details>

`Filter`._`filter`Model
`Filter`._current`Filter`
`Filter`.\_`filter`Component
`Filter`._handle`Filter`TypeChange
**и т.п.**

Д3

2021-02-02 23:18 UTC, AlexMasterov requested changes

2021-02-02 23:18 UTC, AlexMasterov commented on src/main.js
<details>
<summary>model/destinations.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/destinations.js#L3
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/destinations.js#L6
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/destinations.js#L9
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/destinations.js#L13
</details>

`Destinations`._`destinations`
`Destinations`.set`Destinations`
`Destinations`get`Destinations`
**и т.п.**

Д3

```diff
- this._destinations = new Map();
+ this._items = new Map();
```
У методов достаточно просто убрать `Destinations`.

2021-02-02 23:23 UTC, AlexMasterov requested changes

2021-02-02 23:23 UTC, AlexMasterov commented on src/main.js
<details>
<summary>model/filter.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/filter.js#L4
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/filter.js#L7
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/filter.js#L10
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/filter.js#L15
</details>

`Filter`._active`Filter`
`Filter`.set`Filter`
`Filter.get`Filter`
**и т.п.**

Д3

2021-02-02 23:23 UTC, AlexMasterov commented on src/main.js
<details>
<summary>model/offers.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/offers.js#L3
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/offers.js#L6
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/offers.js#L9
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/offers.js#L13
</details>

`Offers`._`offers`
`Offers`.set`Offers`
`Offers`.get`Offers`
**и т.п.**

Д3

2021-02-02 23:23 UTC, AlexMasterov commented on src/main.js
<details>
<summary>model/waypoints.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L3
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L6
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L9
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L14
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L18
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L34
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/waypoints.js#L43
</details>

`Waypoints`._`waypoints`
`Waypoints.`set`Waypoints`
`Waypoints`.get`Waypoints`
**и т.п.**

Д3

> Методы с полным названием класса точно нарушают

2021-02-02 23:32 UTC, AlexMasterov requested changes

2021-02-02 23:32 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/render.js#L46-L47
</details>

Обрати внимание, что здесь сначала идет обращение к `oldChild.parentElement` и только потом `oldChild` проверяется на `null`. Если `oldChild` имеет значение `null` (или отсутствует, `undefiend`), то при обращение к свойству `oldChild.parentElement` будет ошибка:

```js
replace(null, null);
```
```
Uncaught TypeError: Cannot read property 'parentElement' of null
```

Б2, Б7, Д10

См. [старое замечание](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/6#discussion_r543902875):

> Актуальный метод в демо проекте может нарушать [`Д7`](https://up.htmlacademy.ru/ecmascript/13/criteries#d7) и [`Д10`](https://up.htmlacademy.ru/ecmascript/13/criteries#d10)

Функция была исправлена и улучшена, но в одном из заданий возвращена старая реализация 😕

2021-02-02 23:36 UTC, elismountain commented on src/view/edit-waypoint.js
>    _onWaypointTypeChangeHandler(evt) {
Извиняюсь, не перенесла из прошлого коммита, действительно исправляла уже

2021-02-02 23:41 UTC, AlexMasterov requested changes

2021-02-02 23:41 UTC, AlexMasterov commented on src/main.js
<details>
<summary>api/provider.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/api/provider.js#L13
</details>

`acc`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

2021-02-02 23:41 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/statistics.js#L1-L4
</details>

<details>
<summary>utils/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/waypoint.js#L1-L3
</details>

[`Д 11`](https://up.htmlacademy.ru/ecmascript/13/criteries#d11)
> Отсутствует дублирование кода

2021-02-02 23:41 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/offline/offline.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/offline/offline.js#L5
</details>

```js
offlineMessage instanceof Element // true
```
Д6

2021-02-02 23:41 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/toast/toast.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/toast/toast.js#L5
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/toast/toast.js#L10
</details>

```js
toastContainer instanceof Element // true
toastItem instanceof Element // true
```
Д6

2021-02-02 23:42 UTC, AlexMasterov requested changes

2021-02-02 23:42 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/render.js#L33
</details>

```js
wrapper instanceof Element // true
```

Д6

> Исправляли в одном из первых заданий

2021-02-03 00:01 UTC, AlexMasterov requested changes

2021-02-03 00:03 UTC, AlexMasterov requested changes

2021-02-03 00:03 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L371
</details>

```
TypeError: Cannot read property 'get' of undefined
    at Function.parsePointToState (edit-waypoint.js:371)
```
Б2

```
offers // undefined
```
😕

2021-02-03 00:05 UTC, AlexMasterov commented on src/main.js
@elismountain срочно переключись на исправление этого, там каскад ошибок 😟

Из-за этого точки маршрута с сервера не отображаются.

2021-02-03 00:05 UTC, elismountain commented on src/main.js
В остальных модулях тоже оставить только глагол на set, get? Это немного запутывает

2021-02-03 00:11 UTC, AlexMasterov requested changes

2021-02-03 00:11 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L135-L138
</details>

```js
offers       // undefined
destinations // undefined
```
См. внимательно [прошлое замечание](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/11#discussion_r567668075).

<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L46
</details>

Возможно, что нужно так:
```diff
- this._cardEditElement = new EditWaypointView(this.destinations, this.offers, waypoint); 
+ this._cardEditElement = new EditWaypointView(this._destinations, this._offers, waypoint);
```

2021-02-03 00:15 UTC, AlexMasterov commented on src/main.js
См. https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/13#discussion_r569018012

\+

<details>
<summary>model/offers.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/model/offers.js#L13
</details>

```diff
- getOffers() { 
+ get() { 
```

> Это требуется исправить в другом замечание (повторялось)

2021-02-03 00:19 UTC, AlexMasterov requested changes

2021-02-03 00:19 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L375
</details>

```
TypeError: destinations.keys is not a function or its return value is not iterable
    at Function.parsePointToState (edit-waypoint.js:376)
```

Б2

Возможно, что должно быть так:

```diff
- const availableDestinations = [...destinations.keys()];
+ const availableDestinations = [...destinations.get().keys()];
```

См. https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/13#discussion_r568997836

2021-02-03 00:21 UTC, AlexMasterov commented on src/main.js
Нужно из свойств и методов убрать полное название класса (= `Destinations`).

> hint: или изменить название самого класса 😃

Про это уже много раз писал.

См. связанную с этим местом проблему https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/13#discussion_r569021713

2021-02-03 00:23 UTC, elismountain commented on src/main.js
господи,  я дебил ( спасибо

2021-02-03 00:26 UTC, AlexMasterov requested changes

2021-02-03 00:26 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/trip.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/trip.js#L96
</details>

```
TypeError: Cannot read property 'set' of undefined
    at Trip._renderPoint (trip.js:96)
```
Б2

```js
this._pointPresenterMap // undefined
```
😕

Возможно, что нужно так:

```diff
- this._pointPresenterMap.set(waypoint.id, waypointPresenter);
+ this._waypointPresenterMap.set(waypoint.id, waypointPresenter);
```

<details>
<summary>Что-то заработало</summary>

![image](https://user-images.githubusercontent.com/700213/106680222-44182200-65cf-11eb-918a-232d721064ca.png)

</details>

2021-02-03 00:26 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106680254-55f9c500-65cf-11eb-8678-139a4fd7957a.png)

</details>

`INVALID DATE`

Нужно срочно исправить [`formatDurationMs`](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/waypoint.js#L80-L100).

> В первый заданиях была написана рабочая функция, куда она делась 😕

2021-02-03 00:26 UTC, AlexMasterov commented on src/main.js
@elismountain срочно обрати внимание на это замечание.

2021-02-03 00:30 UTC, AlexMasterov requested changes

2021-02-03 00:30 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106680449-ba1c8900-65cf-11eb-822d-525688b8b490.png)

</details>

При нажатие на стрелку вместо открытие формы редактирование удаляется точка маршрута 😕

Нужно исправить.

2021-02-03 00:30 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106680585-e89a6400-65cf-11eb-8a2e-403f83f0898a.png)
</details>

При нажатие на кнопку звездочки (добавить в избранное) выбрасывается исключение:

```
Uncaught TypeError: Cannot read property 'updateData' of null
    at WaypointNew.setSaving (new-waypoint.js:55)
```

Б2

2021-02-03 00:39 UTC, AlexMasterov requested changes

2021-02-03 00:39 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L159
</details>

```js
UserAction.UPDATE_POINT // undefined
```
<details>
<summary>UserAction</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/const.js#L9-L13
</details>

В одном из мест (на выбор) нужно исправить название `UserAction`.

2021-02-03 00:41 UTC, AlexMasterov commented on src/main.js
@elismountain тоже срочно обрати внимание на это замечание.

2021-02-03 00:41 UTC, elismountain commented on src/main.js
oldChild.replaceWith(newChild); ?

2021-02-03 00:46 UTC, AlexMasterov commented on src/main.js
> oldChild.replaceWith(newChild); ?

По ссылки показана полная реализации функции с `.replaceWith`.

В _текущей_ реализации нужно сначала проверить, что `oldChild` не `null`, а только потом получить `oldChild.parentElement`.

2021-02-03 00:51 UTC, AlexMasterov requested changes

2021-02-03 00:51 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L127
</details>

Возможно, что нужно так:
```diff
- this._switchToDisplay();
+ this._switchToEdit();
```

2021-02-03 00:51 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106682197-0917ed80-65d3-11eb-9ed0-2b9b120003bf.png)


</details>

`undefined`

Нужно исправлять.

2021-02-03 00:53 UTC, elismountain commented on src/main.js
сейчас заплачу)

2021-02-03 00:58 UTC, AlexMasterov requested changes

2021-02-03 00:58 UTC, AlexMasterov commented on src/main.js
См. ТЗ:
> Введённые пользователем данные экранируются

Нужно использовать библиотеку `he` для экранирования (sanitize) пользвовательского ввода: поле для указания назначения и поле ввода стоимости

> Полю стоимости в первых заданиях указывали `type="number"`, чтобы его валидировал браузер и не требовало доп. парсить. Но сейчас он снова `type="string"` и это значение парситься `parseInt` (с `type="number`" доступно свойство `.valueAsNumber`, которое сразу возвращает _число_)

2021-02-03 01:00 UTC, AlexMasterov requested changes

2021-02-03 01:03 UTC, AlexMasterov requested changes

2021-02-03 01:03 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/106682890-8728c400-65d4-11eb-8877-b2c9ba43acf3.png)

</details>

<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/106682918-927bef80-65d4-11eb-83e5-43b6dae1e7cb.png)

</details>

Пропал список `offers`. Нужно вернуть и снова сделать как в макете.

> Шаблоны с разметкой были реализованы в первых заданиях 😕

2021-02-03 01:09 UTC, AlexMasterov requested changes

2021-02-03 01:09 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/statistics.js#L54
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/statistics.js#L125
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/statistics.js#L196
</details>

```js
Chart.js:2432 bar chart: "scales.[x/y]Axes.barThickness" is deprecated. Please use "dataset.barThickness" instead
```

Б2

> Please use "dataset.barThickness" instead

2021-02-03 01:17 UTC, elismountain commented on src/main.js
Я видела, но не поняла, какэтим пользоваться. Если заменить barThickness: 44 на dataset.barThickness, то не работает

2021-02-03 01:18 UTC, AlexMasterov requested changes

2021-02-03 01:18 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106683848-56e22500-65d6-11eb-9ca5-fb75c69337c8.png)

</details>

При закрытие формы редактирования по стрелке:
```
render.js:49 Uncaught Error: Can't replace empty elements
    at replace (render.js:49)
```

Нужно исправить.

<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L135
</details>

Возможно, что это поможет:

```diff
- this._switchToEdit(); 
+ this._switchToDisplay(); 
```

В обоих случаях методы были перепутаны 😃

2021-02-03 01:23 UTC, AlexMasterov requested changes

2021-02-03 01:23 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L114
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L122
</details>

При открытии формы редактирования добавляет обработчик `this._escKeyDownHandler`, а при закрытии удаляется `this._handleEscKeyDown`, которого нет (= `undefined`).

В итоге при каждом открытии обработчики на `document` с `Esc` не удаляются и накапливаются.

Б36

Нужно исправить удалять существующий обработчик (метод):

```diff
- document.removeEventListener(`keydown`, this._handleEscKeyDown);
+ document.removeEventListener(`keydown`, this._escKeyDownHandler);
```

> На всякий случай сова напоминаю, что название самих обработчик DOM во всем проекте должны соотвестовать Д3 (нужно использовать _один_ формат именования)

2021-02-03 01:26 UTC, AlexMasterov commented on src/main.js
> Я видела, но не поняла, какэтим пользоваться. Если заменить barThickness: 44 на dataset.barThickness, то не работает

Нужно везде (в похожих местах, из 3) _удалить_ `scales.xAxes.barThickness` и `scales.yAxes.barThickness`. Вместо этого добавить (перенести `barThickness`) в  `dataset`: `dataset.barThickness`.

> Для защите обычно не критично

2021-02-03 01:39 UTC, AlexMasterov requested changes

2021-02-03 01:39 UTC, AlexMasterov commented on src/main.js
При сохранение точки маршрута:

```
trip.js:148 Uncaught TypeError: Cannot read property 'id' of undefined
    at Trip._handleViewAction (trip.js:148)
```

Б2

<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L144-L155
</details>

```js
waypoint // undefined
```

> В прошлых заданиях уже указывал, что тут `undefiend`

<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L307
</details>

Возможно, что это поможет:

```diff
- this._callback.submitForm();
+ this._callback.submitForm(EditWaypoint.parseStateToWayoint(this._state));
```

2021-02-03 01:39 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/presenter/waypoint.js#L138
</details>

Д8

Обработчик событий DOM нужно расположить после _основных_ методов, но до _статических_.

2021-02-03 01:44 UTC, AlexMasterov requested changes

2021-02-03 01:44 UTC, AlexMasterov commented on src/main.js
При удаление точки маршрута:

```
edit-waypoint.js:312 Uncaught TypeError: EditWaypoint.parseStateToWaypoint is not a function
    at EditWaypoint._onResetButtonClickHandler (edit-waypoint.js:312)
```

Б2

<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/edit-waypoint.js#L312
</details>

Похоже, что тут опечатка:

```diff
- this._callback.resetButtonClick(EditWaypoint.parseStateToWaypoint(this._state));
+ this._callback.resetButtonClick(EditWaypoint.parseStateToWayoint(this._state));
```

2021-02-03 01:44 UTC, AlexMasterov commented on src/main.js
После удаления точки маршрута форма редактирования не закрывается, а список точек не перерисововается.

Нужно исправить.

> См. `_handleViewAction` -> `_handleModelEvent`

2021-02-03 02:07 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/observer.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/observer.js#L1
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/utils/observer.js#L3
</details>

`Observer`._`observer`s 

Д3

> Могут придраться

2021-02-03 02:10 UTC, AlexMasterov requested changes

2021-02-03 02:10 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/info.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/e1780e82cbcaee922d5225e2f5a9067cf5b5523e/src/view/info.js#L4
</details>

`export`

Экспортируется, но в проекте (за пределами модуля) не используется.

Б28

```diff
- export const INFO_DESTINATIONS = 3;
+ const INFO_DESTINATIONS = 3;
```

2021-02-03 02:16 UTC, AlexMasterov requested changes

2021-02-03 02:16 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106688331-f3102a00-65de-11eb-96e5-9263e22dd184.png)

</details>

`Invalid Date`

В меню статистики тоже что-то с форматом даты.

Нужно исправить.

2021-02-03 02:21 UTC, elismountain commented on src/main.js
http://joxi.ru/823xqYah9BNY8A   не удаляла вроде, у меня не отображается тоже

2021-02-03 02:26 UTC, AlexMasterov commented on src/main.js
> http://joxi.ru/823xqYah9BNY8A не удаляла вроде, у меня не отображается тоже

Нужно изучать `blame` в Гите.

Возможно, что проще снова реализовать: при создание разметки в шаблоне нужно добавить атрибут `checked` только полю, у которого `type === waypoint.type`.

2021-02-03 02:52 UTC, elismountain commented on src/main.js
В data list тоже удалять все?

2021-02-03 03:09 UTC, AlexMasterov commented on src/main.js
> В data list тоже удалять все?

Там свойства и методы содержат _полное_ название класса (= `DataList`)? (не вижу)

2021-02-03 03:52 UTC, elismountain commented on src/main.js
http://joxi.ru/zANYb3ncvqpnN2   завалилась на этом и сижу (стр 62-77)

  _getWaypoints() {
    const filterType = this._filterModel.get();
    const waypoints = this._waypointsModel.get();
    const filteredWaypoints = filter[filterType](waypoints);

    switch (this._currentSortType) {
      case SortType.DAY:
        return filteredWaypoints.sort(sortWaypointDateAsc);
      case SortType.TIME:
        return filteredWaypoints.sort(sortWaypointDurationDesc);
      case SortType.PRICE:
        return filteredWaypoints.sort(sortWaypointPriceDesc);
      default:
        return filteredWaypoints;
    }
  }

2021-02-03 04:30 UTC, elismountain commented on src/main.js
не получилось разобраться с этой частью. Через консоль лог я вижу офферс, но все равно валятся ошибки

2021-02-03 05:22 UTC, elismountain commented on src/main.js
Алекс, я исправила все до чего смогла добраться, но не эту ошибку. Все равно не работает, даже если только get. Все что в форме, не смогла исправить, так как у меня она таки не открылась ,завтра утром еще попробую, голова уже не варит. Спасибо огромное преогромное за  помощь!

2021-02-03 11:56 UTC, AlexMasterov requested changes

2021-02-03 11:56 UTC, AlexMasterov commented on markup/edit-point.html
> +                          <label class="event__type-label  event__type-label--flight" for="event-type-flight-1"> Flight</label>
Нужно откатить изменение. (убрать пробел перед `Flight`)

2021-02-03 11:56 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106741805-401aed00-662d-11eb-8d2b-87ca637a954d.png)

</details>

После нескольких переходах между меню `Table` и `Stats`, отображение `Stats` остается для `Table`.

Нужно разобраться и исправить.

2021-02-03 11:56 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/smart.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/view/smart.js#L27-L37
</details>

`.replaceChild`

См. внимательно [комментарий](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/13#discussion_r569031724):
> В случае выбора с `.replaceWith` этот метод нужно использовать во всем проекте вместо `.replaceChild` (= Д7)

<details>
<summary>Покажи на что можно исправить</summary>

```js
updateElement() {
  const prevElement = this.getElement();
  this.removeElement();

  const newElement = this.getElement();

  prevElement.replaceWith(newElement);

  this.restoreHandlers();
}
```
</details>

2021-02-03 11:56 UTC, AlexMasterov commented on src/main.js
```
TypeError: Cannot destructure property 'type' of 'waypoint' as it is undefined.
    at createCardTemplate (trip-waypoint.js:26)
```
Б2

<details>
<summary>view/trip-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/view/trip-waypoint.js#L71-L72
</details>

```js
waypoint // undefined
```
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/waypoint.js#L45
</details>

```js
waypoint // undefined
```

Что случилось 😟

2021-02-03 11:56 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +    this._cardEdit = null; //
`//`

Б28

Нужно убрать `//`.

2021-02-03 11:56 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/waypoint.js#L20
</details>

`_destinationsModel`
`_offersModel`

Б28

Нужно удалить.

См. https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/13#discussion_r569018012 + [прошлое замечание](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/11#discussion_r567668075).

2021-02-03 11:56 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/view/edit-waypoint.js#L156-L164
</details>

`on*`

<details>
<summary>presenter/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/waypoint.js#L31
</details>

`*Handler`

Д4, Д6

Весь интенсив прошу выбрать _один_ формат записи обработчиков событий DOM и придерживаться его во всем проекте 😟 Нельзя использовать оба.

2021-02-03 12:00 UTC, AlexMasterov requested changes

2021-02-03 12:05 UTC, AlexMasterov commented on src/presenter/trip.js
> +    // this._renderWaypoint(waypoint);
Почему убран рендер списка точек маршрута?

Сейчас метод `_renderWaypoints` вообще не используется.

2021-02-03 12:20 UTC, AlexMasterov requested changes

2021-02-03 12:20 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/edit-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/view/edit-waypoint.js#L387
</details>

<details>
<summary>presenter/new-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/new-waypoint.js#L28
</details>

`EditWaypoint` неявно работает с моделью и вызывает их методы. Но при создании новой точки маршрута в `EditWaypoint` данные, а не модели, и поэтому у них нет методов `.get`.

<details>
<summary>presenter/new-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/new-waypoint.js#L28
</details>

Это можно быстро исправить:

```diff
- this._cardEdit = new EditWaypointView(offersModel.get(), destinationsModel.get());
+ this._cardEdit = new EditWaypointView(offersModel, destinationsModel);
```


> В MVP view не должна напрямую работать с моделью — для их связывания используется презентер. Архитектура нарушена

2021-02-03 12:22 UTC, AlexMasterov commented on src/main.js
<details>
<summary>presenter/new-waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/2589ee88b28700325caaeb7d00a508512cbb65db/src/presenter/new-waypoint.js#L17
</details>

`*Handler`

Тоже самое. 
Пора уже для всего проекта определиться с именованием обработчиков событий DOM 😃

2021-02-03 12:25 UTC, AlexMasterov requested changes

2021-02-03 12:25 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/106746543-c0445100-6633-11eb-8871-081d16e5135a.png)

</details>

<details>
<summary>Ожидание (markup/add-new-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/106746625-d520e480-6633-11eb-8a43-0b5959ec8368.png)

</details>

У формы для создании новой точки маршрута не должно быть крестика для закрытии.

Нужно убрать. (кнопка должна быть только у формы редактирования)

> Про разницу разметки объяснял в первых заданиях и в чате ТГ

2021-02-03 17:52 UTC, merged