Module2 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #4
Opened 2020-11-25 00:56 UTC by elismountain

Привет! Нужен код ревью, не могу собрать.командер не показывет, что есть ошибки, но консоль ругается

2020-11-26 09:09 UTC, AlexMasterov requested changes

2020-11-26 09:09 UTC, AlexMasterov commented on src/main.js
>  import {createEditFormTemplate} from './view/edit-form.js';
<details>
<summary>view/edit-form.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/dd58666b1af0fbe45ac1a04201ebd61133bd4e44/src/view/edit-form.js#L2
</details>

См. задание:
> Теперь давайте перепишем функцию по созданию шаблона точки маршрута, чтобы она на вход принимала данные — объект определённой структуры

> Аналогичным образом перепишите функцию по созданию шаблона формы редактирования точки маршрута. Обратите внимание на условия поведения того или иного элемента формы, условия описаны в техническом задании

Нужно доработать форму.

2020-11-26 09:09 UTC, AlexMasterov commented on src/main.js
> +
На лекции Игорь показывал и рассказывал, что в отличии от демо-проекта, в личном есть несколько _взаимосвязанных_ структур данных. В твоем проекте это точки маршрута (1), пункты назначения (2) и доп. опции (3).

Нужно генерировать еще две структуры и правильным образом использовать их в шаблонах.

2020-11-26 09:14 UTC, AlexMasterov requested changes

2020-11-26 09:14 UTC, AlexMasterov commented on src/view/card.js
> +        <h3 class="event__title">${type} ${TYPES_STAY.includes(type) ? `in` : `to`} ${city}</h3>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/100331021-b7eeea80-2fe0-11eb-8161-7726f4940c24.png)

</details>

Вместо названия направления — `undefined`.

Нужно разобраться и исправить.

> Вероятно, что проблема на уровне генерации массива или получения случайным образом его элементов по индексу

2020-11-29 01:17 UTC, elismountain commented on src/util.js
> +export const MS_MIN = 86400000;
Если перписать  вот так:

2020-11-29 23:34 UTC, elismountain commented on src/util.js
> +export const calculateTimeDifference = (firstDate, secondDate) => {
Не знаю как пользоваться юиюлиотеками, let - исправила

2020-11-29 23:35 UTC, elismountain commented on src/view/card.js
> +        <h3 class="event__title">${type} ${TYPES_STAY.includes(type) ? `in` : `to`} ${city}</h3>
export const getRandomArrayElement = (arr) => {
  const element = getRandomInteger(0, arr.length - 1);
  return arr[element];
};

2020-11-29 23:39 UTC, elismountain commented on src/view/card.js
>            <img class="event__type-icon" width="42" height="42" src="img/icons/taxi.png" alt="Event type icon">
done. src="img/icons/${type}.png"

2020-11-29 23:57 UTC, elismountain commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
Можно уточнение, пожалуйста, не поняла в чем проблема

2020-11-30 00:16 UTC, elismountain commented on src/view/card.js
> +            <span class="event__offer-title"> ${createOffersTemplate(options)}</span>
тоже не могу разобраться

2020-11-30 01:16 UTC, AlexMasterov commented on src/view/card.js
> +            <span class="event__offer-title"> ${createOffersTemplate(options)}</span>
> не могу разобраться

<details>
<summary>Проблема</summary>

```html
<ul class="event__selected-offers">
  <li class="event__offer">
    <span class="event__offer-title"> </span></li><li class="event__offer">
    <span class="event__offer-title">Switch to comfort class</span>
    +
    €&nbsp;<span class="event__offer-price">150</span>
  </li>
  <li class="event__offer">
    <span class="event__offer-title">Choose seats</span>
    +
    €&nbsp;<span class="event__offer-price">9</span>
  </li>
    +€&nbsp;
    <span class="event__offer-price">92</span>
</ul>
```
</details>

Посмотри внимательно: функция `createOffersTemplate` создает шаблон с вёрсткой `<li class="event__offer">...</li>`, который вставляется в `<li class="event__offer"><span class="event__offer-title">...</span></li>` — в `event__offer-title` такой же части вёрстки.

Чтобы это исправить достаточно оставить только:

```js
<ul class="event__selected-offers">
  ${createOffersTemplate(options)}
</ul>
```

2020-11-30 01:18 UTC, AlexMasterov commented on src/view/card.js
> +        <h3 class="event__title">${type} ${TYPES_STAY.includes(type) ? `in` : `to`} ${city}</h3>
> export const getRandomArrayElement = (arr) => {
> const element = getRandomInteger(0, arr.length - 1);
> return arr[element];
> };

`arr.length - 1` — должно решить эту проблему 👍🏻

2020-11-30 01:25 UTC, elismountain commented on src/view/card.js
> +            <span class="event__offer-title"> ${createOffersTemplate(options)}</span>
спасибо!

2020-11-30 01:27 UTC, AlexMasterov commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
> Можно уточнение, пожалуйста, не поняла в чем проблема

<details>
<summary>Проблема</summary>

```html
<div class="trip-filters__filter">
  <input 
    id="filter-everything" 
    class="trip-filters__filter-input  visually-hidden" 
    type="radio" 
    name="trip-filter" 
    value="everything"
  >
  <label class="trip-filters__filter-label" for="filter-everything">Everything</label>
</div>

<div class="trip-filters__filter">
  <input 
    id="filter-everything" 
    class="trip-filters__filter-input  visually-hidden" 
    type="radio" 
    name="trip-filter" 
    value="everything" 
    checked=""
  >
  <label class="trip-filters__filter-label" for="filter-everything">Future</label>
</div>

<div class="trip-filters__filter">
  <input 
    id="filter-everything" 
    class="trip-filters__filter-input  visually-hidden" 
    type="radio" 
    name="trip-filter" 
    value="everything"
  >
  <label class="trip-filters__filter-label" for="filter-everything">Past</label>
</div>
```
</details>

Посмотри внимательно: у фильтров `Future` и `Past` в атрибутах указан `everything`, т.е. значение другого (первого) фильтра.

2020-11-30 01:45 UTC, elismountain commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
id="${title}" так вроде работает

2020-11-30 01:53 UTC, AlexMasterov commented on src/util.js
> +export const calculateTimeDifference = (firstDate, secondDate) => {
> Не знаю как пользоваться биюлиотеками

<details>
<summary>Покажи пример</summary>

См. [`plugin/duration`](https://day.js.org/docs/ru/plugin/duration):

```js
// utils/date.js
import dayjs from 'dayjs';
import duration from "dayjs/plugin/duration";

dayjs.extend(duration);

export const getDuration = (time) => dayjs.duration(time).$d;
```
Тоже самое:
```diff
- const difference = calculateTimeDifference(startTime, endTime); // [days, hours, minutes]
+ const {days, hours, minutes} = getDuration(endTime - startTime);
```
> К сожалению, у `dayjs` еще нет релиза с поддержкой простого метода форматирования `duration.format`. Мы можем использовать версию библиотеки по коммиту с этим методом, но это нарушит критерий 😟

Обрати внимание, что в твоем решение длительность вычисляется неправильно:

```js
calculateTimeDifference(startTime, endTime); [ days: 3138, hours: 0, minutes: 0, diff: 0 ]
getDuration(endTime - startTime);            { days: 2,    hours: 4, minutes: 18 }
```

Нужно исправить.
</details>

2020-11-30 01:58 UTC, AlexMasterov commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
> ${title}

Тогда вместо `id="filter-future"` будет `id="Future"` 🤔

2020-11-30 02:01 UTC, elismountain commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
все помираю..

2020-11-30 02:10 UTC, AlexMasterov commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-everything">${title}</label>
Попробуй использовать [String.p.`toLowerCase`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) на `title`, чтобы создать значение для атрибутов в нижним регистре:

```diff
+ id: name.toLowerCase(),
  title: name,
```
> Можно добавить `id` при создание структуры или шаблона

Также можно доработать структуру `FILTERS`.

<details>
<summary>Покажи пример</summary>

```js
const FILTERS = [
  {id: `everything`, title: `Everything`, isChecked: true},
  {id: `future`, title: `Future`, isChecked: false},
  {id: `past`, title: `Past`, isChecked: false},
];
```
</details>

2020-12-01 00:49 UTC, AlexMasterov requested changes

2020-12-01 00:49 UTC, AlexMasterov commented on src/view/filter.js
> +       <label class="trip-filters__filter-label" for="filter-${title.toLowerCase()}">${title}</label>
<details>
<summary>generateFilterMarkup</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/filter.js#L7-L8
</details>

3x `title.toLowerCase()`

Создай название в нижним регистре _один_ раз, сохрани в переменную, далее _переиспользуй_:
```js
const id = title.toLowerCase();
```

2020-12-01 00:49 UTC, AlexMasterov commented on src/main.js
См. [прошлое замечание](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/4#discussion_r530827554).

<details>
<summary>view/menu.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/menu.js#L1
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/menu.js#L3
</details>

Нужно сгенерировать массив с данными (объектами) меню в модуле `main.js` и передать его в качестве аргумента `createMenuTemplate`.

<details>
<summary>Покажи ожидание по использованию</summary>

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/main.js#L28
</details>

Нужно реализовать такое:
```js
// main.js
const menuTabs = generateMenuItems(); // только массив с данными (объекты) меню

render(tripControlsMenuElement, createMenuTemplate(menuTabs), `afterend`);
```
</details>

<details>
<summary>view/filter.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/filter.js#L1
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/filter.js#L3
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/filter.js#L14
</details>

Для модуля `view/filter.js` нужно сделать тоже самое.

2020-12-01 00:49 UTC, AlexMasterov commented on src/mocks/const.js
> +export const TRANSPORTS = [`taxi`, `bus`, `train`, `ship`, `transport`, `drive`, `flight`];
`export` const TRANSPORTS

Массив `TRANSPORTS` экспортируется, но используется только в этом модуле.

[`Б 18`](https://up.htmlacademy.ru/ecmascript/13/criteries#b18)
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

Нужно убрать `export`.

> Экспортируй только то, что _явно_ используется в других модулях

2020-12-01 00:49 UTC, AlexMasterov commented on src/view/card.js
> +        <time class="event__date" datetime="${startTime.toISOString()}">${castTimeDateFormat(startTime.getHours())}:${castTimeDateFormat(startTime.getMinutes())}</time>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/100681760-85991080-3385-11eb-8a77-024203c839cf.png)
</details>


<details>
<summary>markup/list.html</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/markup/list.html#L98
</details>

Обрати внимание, что в макете в этом месте используется дата в формате `MAR 18`, но сейчас в этом месте указано время.

Используй библиотеку `days.js` чтобы создать функцию для форматирования даты в нужном формате (= `MAR 18`). Функцию храни в отдельным модуле (см. другое замечание по `days.js`).

> См. [dayjs.`format`](https://day.js.org/docs/ru/display/format) + [примеры в ответах авторах](https://up.htmlacademy.ru/ecmascript/13/module/2/questions)

2020-12-01 00:49 UTC, AlexMasterov commented on src/view/card.js
> +      <button class="event__favorite-btn event__favorite-btn--active" type="button">
<details>
<summary>Звездочка (добавлено в избранное)</summary>

![image](https://user-images.githubusercontent.com/700213/100682461-2c31e100-3387-11eb-99e3-039425e2236e.png)

</details>

Точки маршрута (карточки событий) можно добавлять в избранное, что требуется хранить в данных.

<details>
<summary>mocks/event.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/mocks/event.js#L57-L70
</details>

Добавь тестовым данным свойство `isFavorite` со случайным булевым значением.

<details>
<summary>view/card.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/f5f5f204da88cfb600ea1ecb0b7ef7a6d1752a81/src/view/card.js#L50
</details>

Нужно добавлять класс `event__favorite-btn--active`, используя булевы значения из данных: `isFavourite`. 

Логика: если `isFavourite: false`, то класс не добавляется — точка маршрута не добавлена в избранное.

2020-12-01 18:04 UTC, elismountain commented on src/main.js
>  import {createEditFormTemplate} from './view/edit-form.js';
нужна помощь, остальные замечания исправила.

2020-12-02 01:33 UTC, AlexMasterov requested changes

2020-12-02 01:33 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>createEditFormTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L94
</details>

value="`...`"

Используй значение общей цены из данных.

> Желательно также для поля вместо type="`text`" использовать type="`number`"

2020-12-02 01:33 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>createEditFormTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L83
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L86
</details>

value="`...`"

Сейчас форматировать дату для `value` не обязательно — далее будет использоваться библиотека.

2020-12-02 01:33 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>createEditFormTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L8
</details>

src="img/icons/`flight`.png"

Для названия картинки нужно использовать значение _типа_ точки маршрута из данных.

2020-12-02 01:33 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
В модуле `mock` создай отдельную структуры (массив или объект-словарь) с объектами _всех_ предложений (`offers`) для каждого типа. Для отдельного предложения можно использовать [готовую структуру](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/mocks/event.js#L32).

Эту структуру нужно передать функции `createEditFormTemplate` через доп. аргумент (еще один, да), и
использовать внутри для генерации [разметки предложений](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L105-L149).

<details>
<summary>Логика создания разметки</summary>

Возможно, что это самое сложное 😃

Для режима редактирования и создания новой точки маршрута нужен _общий_ список всех доступных
предложений, с учетом выбранного типа. Такой список потребуется получить с сервера отдельной
структурой (обсуждалось на лекции). Предложения `options` (в твоем случае) в данных точки маршрута считаются уже _выбранными_ (из общего списка).

При редактировании созданной точки маршрута нужно использовать уже _выбранные_ `options` из
данных самой точки и общие `offers[type]` из отдельной структуры. При этом предложения из общего списка не должны дублировать уже выбранные: по названию **и** цене. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.
</details>

2020-12-02 02:33 UTC, AlexMasterov requested changes

2020-12-02 02:33 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>createEditFormTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/view/edit-form.js#L71
</details>

В этом месте нужно использовать значение _типа_ из данных точки маршрута.

> Первую букву типа нужно записать в верхнем регистре: `taxi` -> `Taxi` и т.п. (вроде у тебя уже есть готовая функция)

2020-12-02 21:48 UTC, elismountain commented on src/view/card.js
> +  const {type, city, price, startTime, endTime, options, isFavorite} = card;
isFavorite: getRandomInteger(0, 1) == 1 //строгое сравнение =))

2020-12-03 00:05 UTC, elismountain commented on src/view/card.js
> +          <p class="event__duration">${days === 0 ? `` : `${castTimeDateFormat(days)}D`} ${days + hours === 0 ? `` : `${castTimeDateFormat(hours)}H`} ${castTimeDateFormat(minutes)}M</p>
export const formatDuration = (time) => {
  const {days, hours, minutes} = getDuration(time);
  let result = ``;
  if (days !== 0) {
    result = castTimeDateFormat(days) + `D ` + castTimeDateFormat(hours) + `H ` + castTimeDateFormat(minutes) + `M`;
  } else if (hours !== 0) {
    result = castTimeDateFormat(hours) + `H ` + castTimeDateFormat(minutes) + `M`;
  } else {
    result = castTimeDateFormat(minutes) + `M`;
  }

  return result;
};

2020-12-03 22:54 UTC, elismountain commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
Привет! Можно уточнение. Но у меня же уже есть events функция, в которой рандомно выбирабтся фотографии и описание.
export const generateEvent = () => {
  const randomDate = getRandomDate();

  return {
    type: getRandomArrayElement(TYPES),
    city: getRandomArrayElement(CITIES),
    photos: generatePhotosArray(),
    description: generateDescription(),
    price: getRandomInteger(PRICE_MIN, PRICE_MAX),
    startTime: new Date(randomDate),
    endTime: new Date(getRandomNextDate(randomDate)),
    options: generateAddOptions(),
    isFavorite: getRandomInteger(0, 1) === 1
  };
};

А вызываю я ее в main: 
const CARDS_COUNT = 3;
const events = generateEvents(CARDS_COUNT);

2020-12-04 00:34 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
> Можно уточнение. Но у меня же уже есть events функция, в которой рандомно выбирабтся фотографии и описание

В твоем массиве `events` уже _созданные_ точки маршрута, в которых информация с пунктом назначения (= `city`, `description`, `photos`):

> это _копия_ структуры из общего списка назначений `destinations`, который был выбран и сохранен в данных точки маршрута

В проекте должен быть общий список _всех_ доступных назначений (`destinations`), который представлен отдельной структурой и используется при _создании_ новой точки маршрута или её _редактировании_.

В шаблоне для формы создания и редактирования нужно использовать данные из `destinations`.

2020-12-04 00:47 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
> А вызываю я ее в `main`

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/64e3e2e761c5bd1da1f740c1afb0bb12f20d8a34/src/main.js#L32
</details>

Нужно реализовать что-то вроде этого:

```diff
  const events = generateEvents(CARDS_COUNT);
+ const destinations = generateDestinations();
+ const offers = generateOffers();
```
```diff
- render(tripControlsElement, createNewPointTemplate(), `afterend`);
+ render(tripControlsElement, createNewPointTemplate(events[0], destinations, offers), `afterend`);
```

2020-12-04 01:03 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
> в которой **рандомно** выбирабтся фотографии и описание

Для описания и фотографий в ТЗ есть лишь одна логика: если нет описания или фотографий, т.е. пустая строка и пустой массив, то блоки с их разметкой не отображается (= не создается). Поэтому для удобства тестирования логики следовало генерировать пустую строку и строку с неким текстом, и тоже самое с массивом фотография. Текст описания и ссылки на фотографии вообще не важны.

Вместо этого генерируются всё подрядят, а многое _случайным_ образом, что никак не помогает в реализации логики ТЗ, а только всё усложняет. Не понятно, почему авторы до сих пор делают на этом фокус.

2020-12-04 01:19 UTC, elismountain commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
Это всё очень неудобно и так не делают. = Это очень обнадеживает и радует меня , уже голова кругом, если честно )) Значит, я опять не правильно передалываю.  Я сделала отдельный файл с константами (один, а не два , как было ( для моков и просто) и дописала generateEvent (event.js строка 58) . Сейчас отправлю коммит

2020-12-04 01:22 UTC, elismountain commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
Вы мне так подробно  пишете и объясняете, мне уже неловко ,что я до сих пор не врубаюсь :(

2020-12-04 01:40 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>mocks/event.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/b4596799cd7e4731f003a6e7fd779a6e8ee16ce1/src/mocks/event.js#L63
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/b4596799cd7e4731f003a6e7fd779a6e8ee16ce1/src/mocks/event.js#L71-L74
</details>

`city` нужно вложить в `destination` и переименовать в `name` (или что-то абстрактное), потому что пункт назначения может быть не только город.

Далее используй структуру объекта `destination` для создания массива `destinations`.

2020-12-04 01:44 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>mocks/event.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/b4596799cd7e4731f003a6e7fd779a6e8ee16ce1/src/mocks/event.js#L81
</details>

`date` нужно удалить.

В данных для хранения дат следует использовать объект `Date`, чтобы их можно было удобно использовать для реализации некой логики: сортировка, мат. операции и т.п. Разное форматирование дат следует происходить при создании шаблона.

2020-12-04 01:51 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
<details>
<summary>mocks/event.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/b4596799cd7e4731f003a6e7fd779a6e8ee16ce1/src/mocks/event.js#L65-L70
</details>

`offers` должен хранить массив (= `s`) из объектов:

```js
offers: [
  { 
   type: OFFER_TYPES[getRandomInteger(OFFER_TYPES.length - 1)], 
   title: OTHER_OPTIONS[getRandomInteger(OTHER_OPTIONS.length - 1)], 
   price: getRandomInteger(PRICE_MIN, PRICE_MAX), 
  },
  // ...
]
```

`offerType` следует сократить до `type`.

`checked` следует убрать из данных — предложения в данных точки маршрута считаются выбранными, т.е. не может быть `checked: false`; вместо этого предложение просто удаляется. Но некий флаг `isChecked` может быть удобен для создании шаблона, чтобы в его разметке по условию добавлять атрибут `checked` — при "смешивание" `offers` из точки маршрута и общих создай массив, где каждому объекту добавь этот `isChecked`. (см. логику в других комментариях)

Далее используй структуру объекта `offer` для создания массива `offers`.

2020-12-04 01:53 UTC, AlexMasterov commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
Сейчас будет достаточно создать удобные структуры с правильными типами и использовать их в шаблоне формы редактирование. Логикой можно заняться при выполнении других заданий или в самом конце.

2020-12-04 02:12 UTC, elismountain commented on src/view/edit-form.js
>  export const createEditFormTemplate = () => {
Хорошо, поняла , спасибо! Буду исправлять ))

2020-12-05 02:15 UTC, AlexMasterov commented
Будем дорабатывать в следующих заданиях.

2020-12-05 02:15 UTC, merged