Module3 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #5
Opened 2020-12-08 02:58 UTC by elismountain

Алекс, привет! Помогите, плиз ) 
Сделала дз, следуя демонстарации, но  консоль ругается  на те, компоненты , где я пользуюсь методом map и элементы не отрисовываются.

2020-12-08 12:26 UTC, AlexMasterov requested changes
> консоль ругается на те, компоненты , где я пользуюсь методом map и элементы не отрисовываются

<details>
<summary>Покажи ответ</summary>

<details>
<summary>view/menu.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/menu.js#L3

</details>

Обрати внимание, что функция генерации шаблона использует массив `menuTabs`.

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L30
</details>

Массив передается при создании экземпляра класса (объекта) и доступен как параметр в его конструкторе.

<details>
<summary>view/menu.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/menu.js#L19-L20
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/menu.js#L25
</details>

Но у класса конструктор без параметров и `createMenuTemplate` в методе вызывается без аргумента, т.е. теперь никакого массива не передается и поэтому его значение `undefined`, которые не имеет метода `.map` 😃

Нужно в их конструкторе добавить параметр и и из него получить необходимую структуру, сохранить её в свойство и использовать для функции создания шаблона.

> У некоторых компонентов аналогичная проблема
</details>

2020-12-08 12:26 UTC, AlexMasterov commented on src/main.js
>  const tripCardsElement = document.querySelector(`.trip-events__list`);
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L41
</details>

```js
tripCardsElement // null
```

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L76
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L43
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L73
</details>

```js
taskListElement // null
```

```
render.js:14 Uncaught TypeError: Cannot read property 'append' of null
    at render (render.js:14)
```

🤔

[`Б 2`](https://up.htmlacademy.ru/ecmascript/13/criteries#b2)
> При выполнении кода не возникает необработанных ошибок

2020-12-08 12:26 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L43-L45
</details>
<details>
<summary>view/card.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/card.js#L66-L68
</details>

и т.п.

render`Task`, `task`, `task`Component, `task`EditComponent

В твоем проекте нет _задач_ (`task`), а есть _точки маршрута_ (`point`) 🤔

2020-12-08 12:44 UTC, AlexMasterov requested changes

2020-12-08 12:44 UTC, AlexMasterov commented on src/main.js
> +  render(taskListElement, taskComponent.getElement(), `beforeend`);
<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/utils/render.js#L18
</details>

```diff
- render(taskListElement, taskComponent.getElement(), `beforeend`);
+ render(taskListElement, taskComponent.getElement());
```

2020-12-08 12:44 UTC, AlexMasterov commented on src/main.js
> +import {render, RenderPosition} from "./utils/render.js";
<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/utils/render.js#L1-L5

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/utils/render.js#L18
</details>

```diff
- export const renderTemplate = (container, template, place = `beforeend`) => {
+ export const renderTemplate = (container, template, place = RenderPosition.BEFOREEND) => {
```

2020-12-08 12:44 UTC, AlexMasterov commented on src/main.js
> +import {render, RenderPosition} from "./utils/render.js";
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L24
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L30
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/main.js#L34
</details>

<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/utils/render.js#L4

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/utils/render.js#L8-L15
</details>

Новая функция `render` не обрабатывает `afterend` и поэтому некоторые элементы не добавляются в DOM (и далее недоступны).

Нужно доработать функцию для вставки `afterend.

2020-12-08 12:57 UTC, AlexMasterov requested changes

2020-12-08 12:57 UTC, AlexMasterov commented on src/main.js
> +import EditForm from './view/edit-form.js';
<details>
<summary>view/edit-form.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/edit-form.js#L15
</details>

При создании списка доступных типов маршрута выбранному типу (из данных) нужно добавить атрибут `checked`.

2020-12-08 22:27 UTC, AlexMasterov requested changes

2020-12-08 22:27 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/filter.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/filter.js#L4
</details>

<details>
<summary>view/menu.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/3f5ff41ae09401741727e49b27d4366244a0b217/src/view/menu.js#L5
</details>

`generate`FilterMarkup
`generate`MenuMarkup

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Для названия значений используются английские существительные

Нужно из названия строк с разметкой убрать _глагол_ — это не функция.

2020-12-10 00:34 UTC, elismountain commented on src/main.js
>  const tripCardsElement = document.querySelector(`.trip-events__list`);
Не поняла по этому замечанию, если делаб консоль лог - то показывает правильный класс `.trip-events__list, а не ноль

2020-12-10 00:36 UTC, elismountain commented
Алекс, привет! Я исправила, что смогла, не получилось разобраться с menu.js - не отображается разметка table и stat, ошибок в консоли не вижу

2020-12-10 19:04 UTC, elismountain commented on src/main.js
> +import EditForm from './view/edit-form.js';
Алекс, какая должна быть структура offers? Я исходила из того, что индексация по типу уникальная. Приведите пример, пожалуйста, предложений с одинаковм типом.

2020-12-10 19:53 UTC, AlexMasterov requested changes

2020-12-10 19:53 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/101820892-45315380-3b38-11eb-8adb-54152326d44a.png)

</details>

<details>
<summary>Ожидание (markup\list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/101820964-54180600-3b38-11eb-9ac9-c2419f64ae9c.png)

</details>

Нужно снова исправить разметку, чтобы расположение блоков соотвествовало макету.

2020-12-10 19:53 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/101821195-af49f880-3b38-11eb-8a0f-9cfc1f598f10.png)

</details>

<details>
<summary>Ожидание (markup\list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/101821231-bcff7e00-3b38-11eb-94b2-4437082c439a.png)

</details>

Разметка должна соотвествовать макету. Нужно убрать точку.

2020-12-10 19:53 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/101821703-63e41a00-3b39-11eb-81cb-ed1c8ce3211e.png)

</details>

См. ТЗ:
> Стоимость. **Целое число**

См. [замечание (совет) из прошлого ревью](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/4#discussion_r533826742):
> Также желательно для поля вместо type="`text`" использовать type="`number`"

Нужно исправить.

2020-12-10 19:58 UTC, AlexMasterov commented
> не получилось разобраться с menu.js - не отображается разметка table и stat, ошибок в консоли не вижу

<details>
<summary>Покажи ответ</summary>

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/60a1718fb7b616a726310fb44983d4aa2fd19984/src/main.js#L27
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/60a1718fb7b616a726310fb44983d4aa2fd19984/src/main.js#L30
</details>

```js
tripControlsMenuElement // <h2 class="visually-hidden">...</h2>
```
Элемент компонента меню добавляется в элемент (`tripControlsMenuElement`), которому установлен класс `visually-hidden`, т.е. который _скрыт_ из DOM.

Нужно еще раз внимательно проверить разметку этого блока в макете и добавлять элемент меню в "правильное" место 😃
</details>

2020-12-10 20:01 UTC, AlexMasterov commented on src/main.js
>  const tripCardsElement = document.querySelector(`.trip-events__list`);
> Не поняла по этому замечанию, если делаб консоль лог - то показывает правильный класс `.trip-events__list, а не ноль

До исправления `render` здесь и на этом этапе работы программы был `null`.  (поэтому написал другое замечание с явной подсказкой проблемы)

Вместо `console.log` желательно использовать инструменты разработчика для дебаггинга.

2020-12-10 20:01 UTC, AlexMasterov commented on src/main.js
> +import EditForm from './view/edit-form.js';
Замечание актуально.

2020-12-10 20:01 UTC, AlexMasterov commented on src/main.js
Замечание актуально.

2020-12-10 20:11 UTC, AlexMasterov commented on src/main.js
> +import EditForm from './view/edit-form.js';
> какая должна быть структура offers?

Массив или объект-словарь/[Map](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map). 
(сейчас используется массив, что допустимо, но имеет минусы)

Массив допускает хранение множество объектов с одинаковым типом (возможный кейс) и требует цикла для их нахождения (= `O(N`). Объект-словарь/Map позволяет хранить каждый тип как уникальный ключ, а его значением массив из предложений, что не требует цикла (= `O(1`).

2020-12-10 20:13 UTC, AlexMasterov commented on src/main.js
> +import EditForm from './view/edit-form.js';
> Вместо `for` с `if` нужно выбрать подходящей задаче метод массива.

Замечание актуально: нужно заменить цикл `for` на подходящей задаче метод массива.

2020-12-10 20:27 UTC, AlexMasterov requested changes

2020-12-10 20:27 UTC, AlexMasterov commented on src/main.js
> +import Form from './view/edit-form.js';
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/101825624-e6230d00-3b3e-11eb-945f-af81d934c7ae.png)

</details>

<details>
<summary>Ожидание (markup/add-new-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/101825515-c2f85d80-3b3e-11eb-875a-fd989e054d41.png)

</details>

Нужно вернуть секцию с _описанием_ и _фото_, при этом учесть логику их отображения.

См. макет и логику в [замечание для прошлого задания](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/4#discussion_r533818805).

2020-12-11 02:45 UTC, elismountain commented on src/main.js
> +    if (evt.key === ESC_KEYCODE) {
У меня в прошлой версии было evt.key === `Escape` || evt.key === `Esc`, вы сказали поменять )

2020-12-11 03:14 UTC, elismountain commented on src/view/edit-form.js
> +              <input id="event-type-${waypointType}-1" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${waypointType}" checked>
const createWaypointTypeTemplate = (types) => {
  return types
          .map((waypointType, index) => {
            return `<div class="event__type-item">
              <input id="event-type-${waypointType}-1-${index}" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${waypointType}" ${waypointType === types ? `checked` : ``}>
              <label class="event__type-label  event__type-label--${waypointType}" for="event-type-${waypointType}-1">${waypointType}</label>
            </div>`;
          }).join(``);
};

Написала так , ошибок не валится, но и не работает ))

2020-12-12 00:19 UTC, AlexMasterov requested changes

2020-12-12 00:20 UTC, AlexMasterov commented on src/main.js
Замечание актуально.

2020-12-12 00:20 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/main.js#L34
</details>

<details>
<summary>sort.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/sort.js#L35-L36
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/sort.js#L38
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/sort.js#L42
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/sort.js#L3
</details>

Класс и функция создания шаблона не используют значение из свойства.

Б18

Нужно удалить `point`.

2020-12-12 00:22 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/main.js#L24
</details>

<details>
<summary>view/cost.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/cost.js#L11-L12
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/cost.js#L14
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/cost.js#L18
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/cost.js#L3-L9
</details>

При создание экземпляра класса `Cost` ничего не передается, но у конструктора есть параметр с  `point`, который внутри класса и в шаблоне не используется.

Нужно удалить `point`.

2020-12-12 00:23 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/main.js#L25
</details>

`waypoints[0]` — зачем?

Тоже самое. Удалить здесь и внутри класса.

2020-12-12 00:23 UTC, AlexMasterov commented on src/main.js
> +import EditForm from './view/edit-form.js';
Замечание актуально.

2020-12-12 00:36 UTC, AlexMasterov commented on src/view/edit-form.js
> +              <input id="event-type-${waypointType}-1" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${waypointType}" checked>
> Написала так , ошибок не валится, но и не работает ))

`types` — это массив с доступными типами маршрута (строки), которые здесь используются **в помощь генерации разметки**. На сервере такие "данные" не выдают 😃 

```js
waypointType === types
```

В твоем примере каждый элемент (тип, _строка_) из массива `types` сравнивается с самим массивом. Вместо этого следовало передать в функцию выбранный тип из данных с точкой маршрута и сравнить с ним, что уже было сделано.

2020-12-12 00:40 UTC, AlexMasterov commented on src/main.js
> +    if (evt.key === ESC_KEYCODE) {
> У меня в прошлой версии было evt.key === `Escape` || evt.key === `Esc`, **вы сказали поменять** )

С самого первого замечания наивно ожидал нечто подобное:

> нужно сохранить эти значения (строки) в переменные, записанные в формате констант или использовать перечисление

Но внезапно появились константы с _числом_ для `.keyCode`.

См. [пример, что ожидалось ](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/5#discussion_r541233382) 😃

2020-12-12 00:54 UTC, AlexMasterov commented on src/view/form.js
>    const offerSelectorTemplate = createOfferSelectorTemplate(getOffersByWaypointType(offers, waypoint.type));
Под выходные решил, что дорабатывать логику для `offers` будем в след. задание 😄

Для моральной подготовки прошу перечитать [прошлое замечание](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/4#discussion_r533832851):

> предложения из общего списка не должны дублировать уже выбранные: по названию **и** цене. **Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой**

<details>
<summary>Данные</summary>

```js
const OFFERS = [
  { 
    type: `flight`, 
    offers: [
      { title: `Gravity +20`, price: 100 },
      { title: `Gravity +20`, price: 200 },
    ],
  },
];
```
```js
waypoint[0].offers // { title: `Gravity +20`, price: 100 }
```

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/101967625-5e1b3100-3c2c-11eb-8d2a-8f1b4199de3f.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/101967901-aa1aa580-3c2d-11eb-83de-cd463b715881.png)


</details>

2020-12-12 01:09 UTC, AlexMasterov requested changes

2020-12-12 01:09 UTC, AlexMasterov commented on src/main.js
См. https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/5#discussion_r539980328

2020-12-13 01:03 UTC, elismountain commented on src/view/form.js
> +        <input class="event__input  event__input--price" id="event-price-1" type="number" name="event-price" value="${waypoint.price}">
Спасибо!

2020-12-13 01:12 UTC, elismountain commented on src/main.js
Все равно не поняла, что нужно исправить (

2020-12-13 01:19 UTC, AlexMasterov commented on src/main.js
> Все равно не поняла, что нужно исправить (

Это просто ссылка на старое замечание, которое Гитхаб стал скрыть из-за большого кол. других замечаний. Поэтому добавил наглядную ссылку на него. Сейчас то замечание помечено как разрешенное 😃

По замечанию нужно удалить переменные (аргументы при создании экземпляра класса, параметры его конструктора, свойства), которые определены, но нигде в класса не используются, а некоторые даже не имеют значений (= `undefined`).

2020-12-13 01:23 UTC, elismountain commented on src/main.js
Хорошо, я вроде удалила все.

2020-12-13 01:25 UTC, elismountain commented on src/view/form.js
>            ${offerSelectorTemplate}
Мне нужно написать функцию, путь будет hide, которая будет добавлять класс visually hidden, если пришел пустой массив, правильно?

2020-12-13 01:29 UTC, AlexMasterov commented on src/view/form.js
>            ${offerSelectorTemplate}
> Мне нужно написать функцию, путь будет hide, которая будет добавлять класс visually hidden, если пришел пустой массив, правильно?

Так можно сделать, если работать с DOM-элементами.

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/eaf8f4e871b69c2954969e1e0120ef03950f6958/src/view/form.js#L66

Если создавать шаблона с разметкой (на основе которого потом создаются DOM-элементы), то достаточно этого:

```diff
- const destinationsTemplate = createOptionsTemplate(destinations);
+ const destinationsTemplate = destinations.length > 0 ? createOptionsTemplate(destinations) : ``;
```

😃

2020-12-13 20:16 UTC, AlexMasterov commented
👍🏻

2020-12-13 20:17 UTC, merged

2020-12-13 20:17 UTC, elismountain commented on src/view/form.js
>    const offerSelectorTemplate = createOfferSelectorTemplate(getOffersByWaypointType(offers, waypoint.type));
Привет, ошибки исправила. По последнему замечению, я попробовала создать массив с объектами как в примере выше , но у меня не выпадабт повторения.  Так же переписала структру в форме, чтобы checked был случайный, а не всегда последний, как было до этого 

http://joxi.ru/bmoz5KqI3GpDwr 
http://joxi.ru/V2VLW7NudlgbLr