Module4 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #6
Opened 2020-12-16 03:43 UTC by elismountain

Ready to be checked

Не очень поняла, что делать с remove и replace , добавила их в рендер, но пока  никгде не применяла

2020-12-16 23:43 UTC, AlexMasterov requested changes

2020-12-16 23:43 UTC, AlexMasterov commented on src/main.js
>      document.addEventListener(`keydown`, onEscKeyDown);
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/71942d79edcf70c66604130b1803d981d7cb12a3/src/main.js#L52
</details>

<details>
<summary>view/form.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/71942d79edcf70c66604130b1803d981d7cb12a3/src/view/form.js#L160
</details>

и т.д.

`onEscKeyDown`

[`Д 6`](https://up.htmlacademy.ru/ecmascript/13/criteries#d6)
> Стиль именования переменных **сохраняется во всех модулях**

> не следует мешать обработчики содержащие `Handler` и `on`

В других местах проекта для именования обработчиков событий DOM _уже_ используется формат записи с `*handler`.

В этом случае нужно здесь тоже его использовать. (или исправить в других местах)

> Прошу внимательно следить за этим

2020-12-16 23:43 UTC, AlexMasterov commented on src/main.js
<details>
<summary>markup/stats.html</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/71942d79edcf70c66604130b1803d981d7cb12a3/markup/stats.html#L69-L83
</details>

Нужно заранее реализовать компонент с созданием этой разметки, но использовать её пока не обязательно.

2020-12-16 23:43 UTC, AlexMasterov commented on src/utils/render.js
> +export const render = (container, child, place) => {
[Повтор](https://github.com/htmlacademy-ecmascript/89110-big-trip-13/pull/5#discussion_r538107324) 😃

<details>
<summary>render</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/71942d79edcf70c66604130b1803d981d7cb12a3/src/utils/render.js#L18-L28
</details>

<details>
<summary>Расскажи, что можно улучшить</summary>

На случай отсутствия доступной позиции для рендера (`position`) выбрасывай исключение (ошибку):
```js
throw new Error(`Unknown render position: ${place}`);
```
Это можно сделать как `default` в `switch` или после него.
</details>

2020-12-17 01:32 UTC, AlexMasterov requested changes

2020-12-17 01:32 UTC, AlexMasterov commented on src/view/filter.js
>      this._filter = filterTabs;
`Filter`._`filter`

Д3

2020-12-21 09:49 UTC, AlexMasterov requested changes

2020-12-21 09:49 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/102761307-cd5cf780-4387-11eb-9122-69cca06e5ec6.png)

</details>

<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/102758110-4b6acf80-4383-11eb-9315-02a59b1c7be6.png)

</details>

Нужно название типов записать с заглавной буквы (= исправить регистр первый буквы).

2020-12-21 09:49 UTC, AlexMasterov commented on src/view/form.js
> +  const merge = (array) => {
`array`

Б8 😟

2020-12-21 09:49 UTC, AlexMasterov commented on src/view/form.js
> +  const merge = (array) => {
<details>
<summary>createOfferSelectorTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/1c1b238283ff728f1ac7f895fa136f5628df0484/src/view/form.js#L23-L25

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/1c1b238283ff728f1ac7f895fa136f5628df0484/src/view/form.js#L27
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/1c1b238283ff728f1ac7f895fa136f5628df0484/src/view/form.js#L35-L44
https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/1c1b238283ff728f1ac7f895fa136f5628df0484/src/view/form.js#L46-L47
</details>
<details>
<summary>createOfferSelectorTemplate</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/1c1b238283ff728f1ac7f895fa136f5628df0484/src/view/form.js#L51
</details>

⏳ (потребуется доработка)

2020-12-22 06:40 UTC, AlexMasterov requested changes

2020-12-22 06:40 UTC, AlexMasterov commented on src/mocks/const.js
> +export const MESSAGE = {
`MESSAGE`

[`Б 7`](https://up.htmlacademy.ru/ecmascript/13/criteries#b7)
> Перечисления (Enum) названы английскими существительными и **начинаются с прописной (заглавной) буквы**

> \+ Это не моковые данные. Нужно найти другое место

2020-12-22 06:40 UTC, AlexMasterov commented on src/view/card.js
> +    this.getElement().querySelector(`.event__rollup-btn`).addEventListener(`click`, this._onRollupButtonClickHandler);
this._`on`RollupButtonClickHandler

[`Д 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#d4)
> Для именования нескольких обработчиков используется `on` **или** `handler` и описание события

[`Д 6`](https://up.htmlacademy.ru/ecmascript/13/criteries#d6)
> не следует мешать обработчики содержащие `Handler` **и** `on`

Нужно из названия обработчика убрать убрать `on`.

2020-12-22 06:40 UTC, AlexMasterov commented on src/view/form.js
> +            const ucTypes = waypointType.charAt(0).toUpperCase() + waypointType.slice(1);
```js
typeof ucTypes // string
```

`uc`Type`s`

[`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4)
> Сокращения в словах запрещены

Нужно из названия убрать убрать сокращение и множ. число.

2020-12-22 06:40 UTC, AlexMasterov commented on src/view/form.js
> +  const merge = (arrays) => {
`arrays`

Масло маслинное. Функция принимает _один_ массив, а не массивы 🤔

2020-12-22 19:43 UTC, elismountain commented on src/view/form.js
> +  const merge = (arrays) => {
Исправила на оферс, но что не так было с массивами - это существительно во множественном числе, разе нет?

2020-12-22 19:44 UTC, elismountain commented on src/mocks/const.js
> +export const MESSAGE = {
В конст сложила из за прошлого коментария, вы написали //const.js

2020-12-22 21:02 UTC, AlexMasterov commented on src/utils/message.js
> +export const LoadingMessages = {
LoadingMessage`s`

[`Б 7`](https://up.htmlacademy.ru/ecmascript/13/criteries#b7)
> Перечисления названы существительными в единственном

2020-12-22 21:02 UTC, AlexMasterov commented on src/view/form.js
> +  const merge = (arrays) => {
Отвечу здесь или в чате, как освобожусь 😃

2020-12-22 21:03 UTC, AlexMasterov approved these changes
Пожалуйста, мелкое замечание в остатке исправь при выполнении следующего задания.

2020-12-22 21:04 UTC, AlexMasterov commented on src/view/form.js
> +  const merge = (arrays) => {
Отвечу здесь или в чате, как освобожусь 😃

2020-12-22 21:04 UTC, merged