Module5 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #7
Opened 2020-12-26 03:47 UTC by elismountain

Алекс, привет!

Можно, пожалуйста, ревью кода по первой части,  пока я все окончательно не удалила из main )  Сложное задание, не до конца понимаю чего мы все туда-сюда переносим )) Еще вопрос, достаточно ли в модуль point поместить только одну форму, или там еще что то должно быть ? 

Я так же переписала Sort и обавила обработчики на звездочку

Спасибо!

2020-12-26 18:35 UTC, AlexMasterov requested changes

2020-12-26 18:35 UTC, AlexMasterov commented on src/view/card.js
> +    this._callback.favoriteClick = callback;
this._callback.`favoriteClick`

Б10

Нужно в название метода поставить глагол в начало.

2020-12-26 18:35 UTC, AlexMasterov commented on src/view/sort.js
> +  const createSortingTemplate = sorting.map((sort) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/103157177-70b36f80-47c1-11eb-8cb7-d3e50524adde.png)

```
sort.js:5 Uncaught TypeError: Cannot read property 'map' of undefined
    at createSortingContainerTemplate (sort.js:5)
```
</details>

Б2

Нужно разобраться и исправить.

2020-12-26 18:35 UTC, AlexMasterov commented on src/presenter/trip.js
> +  _renderSort() {
<details>
<summary>presenter/trip.js</summary>

```js
import Sort from './view/sort.js';
```
</details>

Для работы с `SortView` (и логикой сортировки) нужно создать отдельный презентер.

2020-12-26 18:35 UTC, AlexMasterov commented on src/presenter/point.js
> +    this._tripListContainer = tripListContainer;
```js
tripListContainer instanceof Element // true
```
Д6

Нужно добавить `Element`.

2020-12-26 18:35 UTC, AlexMasterov commented on src/main.js
> достаточно ли в модуль point поместить только одну форму, или там еще что то должно быть ?

Если этого достаточно для реализации ТЗ.

<details>
<summary>markup\add-new-point.html</summary>

![image](https://user-images.githubusercontent.com/700213/103157056-5dec6b00-47c0-11eb-87b4-6c2471870877.png)

</details>

<details>
<summary>markup\edit-point.html</summary>

![image](https://user-images.githubusercontent.com/700213/103157038-2da4cc80-47c0-11eb-89a2-a167864a188b.png)

</details>

Разметка формы должна соотвествовать макетам.

Нужно придумать способ, как это сделать. (подсказывал в чате)

> Главное реализовать _формальные_ требования ТЗ

2020-12-26 18:35 UTC, AlexMasterov commented on src/main.js
См. задание:

> Разнесите по презентерам всю логику по отрисовке точек маршрута, а также по навешиванию на них обработчиков, из `main.js`

> В `main.js` создайте экземпляры презентеров, передайте данные и инициализируйте их

Нужно доработать.

2020-12-26 18:40 UTC, AlexMasterov requested changes

2020-12-26 18:40 UTC, AlexMasterov commented on src/main.js
>  render(tripControlsElement, new Filter(filterTabs).getElement(), RenderPosition.AFTERBEGIN);
Для `FilterView` нужно создать отдельный презентер.

2020-12-26 18:40 UTC, AlexMasterov commented on src/main.js
> +render(tripEventsElement, new Sort(sorting).getElement(), RenderPosition.AFTERBEGIN);
<details>
<summary>presenter/trip.js</summary>

```js
import Sort from './view/sort.js';
```
</details>

Для работы с `SortView` (и логикой сортировки) нужно создать отдельный презентер.

2020-12-26 18:44 UTC, AlexMasterov requested changes

2020-12-26 18:44 UTC, AlexMasterov commented on src/main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/21bdb234e4c73e2e092882fe08edbf9752c6c039/src/main.js#L44-L46
</details>

Вместо этого нужно создавать разметку с помощью компонентов.

Вместо `document.querySelector` нужно использовать ссылку на созданный элемент с разметкой.

2020-12-26 18:45 UTC, AlexMasterov requested changes

2020-12-26 18:45 UTC, AlexMasterov commented on src/main.js
>  render(tripEventsElement, new Form(waypoints[0], destinations, waypointTypes, offers).getElement(), RenderPosition.BEFOREEND);
<details>
<summary>utils/render.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/21bdb234e4c73e2e092882fe08edbf9752c6c039/src/utils/render.js#L9-L16
</details>

Использование `render` можно упростить:
```diff
- render(tripEventsElement, new Form(waypoints[0], destinations, waypointTypes, offers).getElement(), RenderPosition.BEFOREEND);
+ render(tripEventsElement, new Form(waypoints[0], destinations, waypointTypes, offers));
```

2020-12-26 18:49 UTC, AlexMasterov commented on src/view/sort.js
> +          <input id="sort-${name}" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="sort-${name}" ${isChecked ? `checked` : ``} ${isDisabled ? `disabled` : ``}>
id="`sort-`${name}"
value="`sort-`${name}"

Можно убрать `sort-`, чтобы потом в обработчике упростить логику с их обработкой.

2020-12-26 18:52 UTC, AlexMasterov commented on src/view/sort.js
> +    // сортировать по цене?
Сортировать по цене нужна.

<details>
<summary>view/sort.js</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/21bdb234e4c73e2e092882fe08edbf9752c6c039/src/view/sort.js#L9
</details>

type="`radio`"

Вместо `click` советую использовать делегирование на `change` с одним обработчиком.

2020-12-28 02:34 UTC, elismountain commented on src/view/sort.js
> +    // сортировать по цене?
Алекс, спрасибо за проверку.  Стараюсь сиправлять в свободные минутки, не много их правда (

2021-01-15 00:46 UTC, closed without merging