Module5 task1
htmlacademy-ecmascript/89110-big-trip-13 pull request #8
Opened 2021-01-17 06:12 UTC by elismountain

Добрый день Александр,

Я переписала все пятое задание, так как окончательно запуталась. На то, что я сдам проект уже надежд нет, но может хоть в MVP разбурусь (

2021-01-19 11:39 UTC, AlexMasterov requested changes
Отметил только самый простые замечания, которые для защиты проекта нужно исправить в первую очередь.

2021-01-19 11:39 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/105029611-9f8cd080-5a63-11eb-82a0-d0097b2b36e4.png)

</details>

```
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

Б1, Б2

Нужно разобраться и исправить.

2021-01-19 11:39 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/105029684-b7fceb00-5a63-11eb-9a4b-f6a17161c970.png)
</details>

`INVALID DATE`

Б1

Нужно разобраться и исправить.

2021-01-20 03:03 UTC, elismountain commented on src/utils/event.js
> +  waypoints.forEach((evt) => destinations.push(evt.destination));
Допустимые сокращения: evt для объектов Event и его производных (MouseEvent, KeyboardEvent и подобные)

2021-01-20 10:06 UTC, AlexMasterov commented on src/utils/event.js
> +  waypoints.forEach((evt) => destinations.push(evt.destination));
Сокращение `evt` зарезервировано и допускается для именования первого параметра функций, которые используются как обработчики (коллбэки) событий DOM; значением `evt` является объект типа [`Event`](https://developer.mozilla.org/ru/docs/Web/API/Event), включая [интерфейсы основанные на `Event`](https://developer.mozilla.org/ru/docs/Web/API/Event#introduction).

```js
evt instanceof Event // false
```
Здесь пользовательская функция и параметр коллбэка для метода массива `Array.p.forEach`, который никак не может быть событием DOM.

2021-01-20 10:13 UTC, AlexMasterov commented on src/utils/event.js
> +    const priceForWaypointOffers = Array.from(waypoint.offers).reduce((sum, offer) => sum + OFFERS.get(offer).price, 0);
При вычисление общей стоимости нужно использовать только данные из точек маршрута: базовую стоимость + стоимость каждого доп. предложения. Доступный список `OFFERS` не используется (в прошлых PR/заданиях объяснял, зачем он нужен).

Поэтому реализовано неправильно.

> Это доп. задание, которое необязательно для защиты

2021-01-20 10:22 UTC, AlexMasterov commented on src/utils/event.js
> +  waypoints.forEach((evt) => destinations.push(evt.destination));
<details>
<summary>getDestinationsForTrip</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/90334bfd694e2fcfa7b6a29b21d501c98597d42f/src/utils/event.js#L32-L34
</details>

`Array.p.forEach`

Д24

Подобные задачи решаются через `Array.p.map`.

2021-01-20 10:43 UTC, AlexMasterov commented on src/utils/event.js
> +  waypoints.forEach((evt) => destinations.push(evt.destination));
<details>
<summary>getDestinationsForTrip</summary>

https://github.com/htmlacademy-ecmascript/89110-big-trip-13/blob/90334bfd694e2fcfa7b6a29b21d501c98597d42f/src/utils/event.js#L28-L30
</details>

Д10

Ad-hoc валидация ведёт к феномену, который специалисты в области теоретико-языковой безопасности называют _парсинг наугад:_

> Парсинг наугад — это [антипаттерн](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D1%82%D0%B8%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD), в котором код, выполняющий парсинг и валидацию, перемешан с бизнес логикой; Разработчики пишут пачки проверок на входные аргументы, в надежде (без какого-либо формального обоснования), что так или иначе эти проверки поймают все "плохие" случаи

Сейчас структуры (и типы значений) зафиксированы в "моках". При получение данных с сервера будет происходить их парсинг в эти структуры, а их значения будут явно приводиться. Эта функция находится в модуле с названием `event.js`, что указывает на её контекст использования, _как ограничение_. Поэтому компоненты могут полагаться на фиксированную структуру и тем самым избежать лишний проверок и доп. логики.

Вместо `!waypoints` следует использовать параметр (значение) по умолчанию: `[]`.
Проверку `waypoints.length === 0` при необходимости следует делать на уровне выше, чтобы функцию вообще не вызывать.

Возвращать два разных типа из одной функции: `null` и `[]` — это плохой дизайн функции, который вынуждает писать больше лишний логики. С `null` вообще наблюдается большое непонимание на интенсиве 😟

2021-01-20 11:00 UTC, AlexMasterov commented on src/view/trip-waypoint.js
> +      .addEventListener(`click`, this._favoriteClickHandler);
.event__`favorite-btn` + `click` !==this._`favorite`ClickHandler

Д4

2021-01-22 04:00 UTC, AlexMasterov approved these changes

2021-01-22 04:01 UTC, merged

2021-01-30 19:50 UTC, elismountain commented on src/main.js
> +document.querySelector(`.trip-main__event-add-btn`).addEventListener(`click`, (event) => {
А как лучше назвать переменую? Элемент? В демонстарциях ивенты везде

2021-01-30 19:56 UTC, AlexMasterov commented on src/main.js
> +document.querySelector(`.trip-main__event-add-btn`).addEventListener(`click`, (event) => {
> А как лучше назвать переменую?

См. [`Б 4`](https://up.htmlacademy.ru/ecmascript/13/criteries#b4):
> `evt` для объектов [`Event`](https://developer.mozilla.org/ru/docs/Web/API/Event) и его производных (MouseEvent, KeyboardEvent и подобные)

2021-01-30 19:56 UTC, AlexMasterov commented on src/main.js
> +document.querySelector(`.trip-main__event-add-btn`).addEventListener(`click`, (event) => {
> В демонстарциях ивенты везде

Можно ссылку?